# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ti'an 
subtitle: 层楼终究误少年，自由早晚乱余生
description: 层楼终究误少年，自由早晚乱余生
keywords: Ti'an,兲,Thaddeus，Blog
author: Ti'an
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: http://thaddeus.ink
root: /
## 建议不要按照日期归档分类
#permalink: :year/:month/:day/:title/  # 默认永久链接冗长，title中存在中文字符。
#permalink: :id.html # 尽量短，层次少，全小写，中划线连字，具有描述性，包含关键词
# permalink_defaults:
permalink: post/:abbrlink.html   # 生成唯一链接
permalink_defaults:
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex

pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source  # 源文件夹，内容存储 
public_dir: public  # 公用文件夹，静态网站生成
tag_dir: tags       # 标签目录
archive_dir: archives # 归档目录
category_dir: categories  # 分类目录
code_dir: downloads/code  # 代码目录
i18n_dir: :lang 
skip_render:    # 被复制到public而不进行渲染
  - README.md
  - CNAME
  - mainfest.json
  - background.css

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
# auto_spacing: false 中英文之间加入空格
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0  # 把文件名转换为 1 小写 2 大写
render_drafts: false # 显示草稿
post_asset_folder: false # 启用Asset文件夹
relative_link: false #把链接改为与根目录相对位置
future: true  # 显示未来的文章
highlight:  # 代码块设置 Highlight.js
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:    # 代码块设置 PrismJS
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag  
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'date'
# mtime 使用文件的最后修改时间
# date 推荐可被用于Git工作流
# empty 不使用updated

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include: 
# exclude: 
# ignore: 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly
# theme: landscape
# theme_config: _config.next.yml

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Lansm/Lansm.github.io.git
  branch: master

aplayer:
  meting: true
  asset_inject: false

search:
  path: search.xml
  field: all
  content: true

# RSS hexo-generator-feed
feed: 
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# hexo-filter-nofollow
nofollow:
  enable: true
  field: site
  exclude:
    - ''
    - ''

# hexo-generator-sitemap
sitemap:
  path: sitemap.xml
  # template: ./sitemap_template.xml
  rel: false
  tags: true
  categories: true

# baidusitemap
baidusitemap:
  path: baidusitemap.xml


# PWA
# offline config passed to sw-precache.
offline:
  maximumFileSizeToCacheInBytes: 10485760 # 缓存的最大文件大小，以字节为单位
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,jpeg,gif,svg,webp,eot,ttf,woff,woff2}
  # 静态文件合集，如果你的站点使用了例如webp格式的文件，请将文件类型添加进去。
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /* # 如果你需要加载CDN资源，请配置该选项，如果没有，可以不配置。
      handler: cacheFirst
      options:
        origin: thaddeus.ink # 可替换成你的 url

# Security
encrypt: # hexo-blog-encrypt
  abstract: Secret #有东西被加密了, 请输入密码查看.
  message: Sth need password #您好, 这里需要密码.
  # tags:
  # - {name: novel , password: tianaz}
  # template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 你不对劲 #抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 你确实不对劲 #抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# hexo-hide-posts
hide_posts:
  # 可以改成其他你喜欢的名字
  filter: secret
  # 指定你想要传递隐藏文章的 generator，比如让所有隐藏文章在存档页面可见
  # 常见的 generators 有：index, tag, category, archive, sitemap, feed, etc.
  public_generators: [tag,category,archive,sitemap,feed]
  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: false