# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ti'an 
subtitle: I'm who I am, I'm the Ti'an.
description: I'm who I am, I'm the Ti'an.
keywords: Ti'an,兲,Thaddeus，Blog
author: Thaddeus
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://thaddeus.ink
root: /
## 按照日期归档分类
#permalink: :year/:month/:day/:title/  # 默认永久链接冗长，title中存在中文字符。
#permalink: :id.html # 尽量短，层次少，全小写，中划线连字，具有描述性，包含关键词

permalink: post/:abbrlink.html   # 生成唯一链接
permalink_defaults:
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: dec    # 进制：dec(default) and hex

# Directory
source_dir: source  # 源文件夹，内容存储 
public_dir: public  # 公用文件夹，静态网站生成
tag_dir: tags       # 标签目录
archive_dir: archives # 归档目录
category_dir: categories  # 分类目录
code_dir: downloads/code  # 代码目录
i18n_dir: :lang 
skip_render:    # 被复制到public而不进行渲染
  - CNAME
  - google007a6d66e70d8be5.html
  - README.md
  - robots.txt
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Next
# theme: Annie


##sitemap
baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Lansm/Lansm.github.io.git
  branch: master


# search:
#   path: search.json
#   zipPath: search.zip
#   versionPath: searchVersion.txt
#   field: post
  #field: post, page or all
search:
  path: search.xml
  field: post
  format: html
  limit: 10000


###  RSS订阅插件
# npm install hexo-generator-feed --save
# feed:
#     type: atom
#     path: atom.xml
#     limit: 20




# Markdown-it config
# Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-task-lists
  anchors:
    level: 2
    collisionSuffix: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ¶


# 窗口隐藏和可见时候 改标题和图标
# Change title and favicon when window is hidden and visible.
title_change:
  enable: true

  # Enabling this feature on non-desktop devices may not be a good choice, but it depends on you.
  onmobile: false

  # Enable random title or not.
  # Basically `random: true` means you have several titles to display and `random: false` means you have only one title to display.
  # When `random: true`, YOU MUST FOLLOW the format which has been commented in two title options below.
  # When `random: false`, please fill in the same line of the title option, like `title: one title`.
  random: true

  # Restore the original title after the specified time in milliseconds.
  timeout: 2019

  # Options when window is hidden.
  hidden:
    favicon: /images/tian_updown.png
    title:
      - 404
      - φ(*￣0￣)
      - Waiting for you.

  # Options when window is visible.
  visible:
    favicon: /images/tian.png
    title:
      - 200
      - (✿◡‿◡)
      - Welcome back!


